# Generated by Django 4.1.4 on 2022-12-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='image',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
